log:
  level: trace

api:
  listen: ":1984"

rtsp:
  listen: ":8554"
  strict: false
  publish:
    - username: publisher
      password: secret

webrtc:
  listen: ":8555"
  candidates:
    - ${GO2RTC_CANDIDATE:-}
  ice_servers:
    - urls:
        - stun:stun.l.google.com:19302

streams:
  cam1_raw:
    - rtsp://localhost:8554/cam1_raw
  "cam1_raw?rtsp_transport=tcp":
    - rtsp://localhost:8554/cam1_raw
  cam1_overlay:
    - rtsp://localhost:8554/cam1_overlay
  "cam1_overlay?rtsp_transport=tcp":
    - rtsp://localhost:8554/cam1_overlay
