go2rtc:
  log:
    level: trace
  webrtc:
    listen: ":8555"
    candidates:
      - ${GO2RTC_CANDIDATE:-}
    ice_servers:
      - urls:
          - stun:stun.l.google.com:19302
  rtsp:
    strict: false
    publish:
      - username: publisher
        password: secret
  streams:
    cam1_raw:
      - rtsp://localhost:8554/cam1_raw
    "cam1_raw?rtsp_transport=tcp":
      - rtsp://localhost:8554/cam1_raw
    cam1_overlay:
      - rtsp://localhost:8554/cam1_overlay
    "cam1_overlay?rtsp_transport=tcp":
      - rtsp://localhost:8554/cam1_overlay
