log:
  level: trace

api:
  listen: ":1984"

rtsp:
  listen: ":8554"
  strict: false
  publish:
    - username: publisher
      password: secret

webrtc:
  listen: ":8555"
  candidates:
    - ${GO2RTC_CANDIDATE:-}
  ice_servers:
    - urls:
        - stun:stun.l.google.com:19302

streams:
  cam1_raw:
    - rtsp://publisher:secret@127.0.0.1:8556/cam1_raw
  cam1_overlay:
    - rtsp://localhost:8556/cam1_overlay
  cam1overlay:
    - rtsp://127.0.0.1:8556/cam1overlay
 

